library(imputeTS)
> library(readxl)
> Input_Data <- read_excel("C:/Users/Юля/Desktop/Input Data.xlsx")
> tsInput_Data4 <- ts( Input_Data [,4], start=2010, frequency = 12 )
> plot(tsInput_Data4)
> tsInput_Data4mid <- na_mean(tsInput_Data4, option = "mean", maxgap = Inf)
> plot(tsInput_Data4mid)
> tsInput_Data4season <- na_seasplit( tsInput_Data4, algorithm = "interpolation", find_frequency = FALSE, maxgap = Inf )
> plot(tsInput_Data4season)
> stl(tsInput_Data4season [,1], t.window=13, s.window="periodic", robust=TRUE)
> perem <- stl(tsInput_Data4season [,1], t.window=13, s.window="periodic", robust=TRUE) 
> plot (perem)